import { readFile } from "node:fs/promises";
import path from "node:path";

import { ImageResponse } from "next/og";

import { CHECK_COUNT } from "@/lib/scan-facts";

/**
 * The social card: wordmark, one line of positioning, and the one claim worth
 * making — that every check is passive.
 *
 * Generated by next/og at build time rather than committed as a PNG, so it
 * cannot drift from the copy it quotes; the check count comes from the same
 * constant the home page uses.
 */
export const alt = "Surfaced — passive attack surface scanner";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

/**
 * Satori has no default font, so one has to be supplied. The file is copied
 * into assets/ rather than read from node_modules — see assets/README.md for
 * why that matters once a route is traced as dynamic.
 */
async function loadMono(): Promise<ArrayBuffer> {
  const file = await readFile(
    path.join(process.cwd(), "assets", "GeistMono-Medium.ttf"),
  );
  return Uint8Array.from(file).buffer;
}

export default async function OpenGraphImage() {
  const mono = await loadMono();

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "0 96px",
          // Literal token values — an image generated outside the document
          // cannot read CSS custom properties. bg / fg / fg-muted / accent.
          background: "#0a0b0d",
          fontFamily: "GeistMono",
        }}
      >
        <div style={{ display: "flex", alignItems: "center" }}>
          <div style={{ fontSize: 76, color: "#e8eaed", letterSpacing: "-0.02em" }}>
            surfaced
          </div>
          <div
            style={{
              width: 26,
              height: 62,
              marginLeft: 14,
              borderRadius: 4,
              background: "#8e81f7",
            }}
          />
        </div>

        <div
          style={{
            marginTop: 36,
            fontSize: 30,
            lineHeight: 1.45,
            color: "#a8b0ba",
            maxWidth: 880,
          }}
        >
          See what your domain reveals to anyone who looks — DNS, headers,
          certificates — scored and ranked, without touching your systems.
        </div>

        <div
          style={{
            marginTop: 52,
            display: "flex",
            alignItems: "center",
            fontSize: 21,
            letterSpacing: "0.08em",
            color: "#8b939e",
          }}
        >
          {`${CHECK_COUNT} PASSIVE CHECKS`}
          <span style={{ margin: "0 16px", color: "#343a42" }}>·</span>
          READ-ONLY
          <span style={{ margin: "0 16px", color: "#343a42" }}>·</span>
          NOTHING SENT TO YOUR SERVERS
        </div>
      </div>
    ),
    {
      ...size,
      fonts: [{ name: "GeistMono", data: mono, style: "normal", weight: 500 }],
    },
  );
}
